Repository nanoframework/Windows.Storage, pull requests merged in 2019-04, with the labels that each got.

#30 Add event manager
  source/Windows.Storage/RemovableDeviceEventArgs.cs
  source/Windows.Storage/StorageEventManager.cs
  source/Windows.Storage/Windows.Storage.nfproj
  source/Windows.Storage/packages.config
  source/nanoFramework.Windows.Storage.sln
  tests/RemovableDeviceEvent/Program.cs
  tests/RemovableDeviceEvent/Properties/AssemblyInfo.cs
  tests/RemovableDeviceEvent/RemovableDeviceEvent.nfproj
  tests/RemovableDeviceEvent/packages.config
Labels: Type: enhancement

#31 Add missing dependency in nuspec
  source/nanoFramework.Windows.Storage.DELIVERABLES.nuspec
  source/nanoFramework.Windows.Storage.nuspec
Labels: Type: bug

#32 Add Storage.Devices to support ESP32 mount operations
  source/Windows.Storage/FileIO.cs
  source/Windows.Storage/IStorageProvider.cs
  source/Windows.Storage/KnownFolderId.cs
  source/Windows.Storage/KnownFolders.cs
  source/Windows.Storage/StorageDevices.cs
  source/Windows.Storage/StorageFile.cs
  source/Windows.Storage/StorageFolder.cs
  source/Windows.Storage/Windows.Storage.nfproj
Labels: Type: enhancement

#33 Implement new methods in StorageFolder and StorageFile
  source/Windows.Storage/IStorageItem.cs
  source/Windows.Storage/StorageFile.cs
  source/Windows.Storage/StorageFolder.cs
Labels: Type: enhancement

#35 Bumps nanoFramework.Runtime.Events from 1.0.5-preview-019 to 1.0.6-preview-001
  source/Windows.Storage/Windows.Storage.nfproj
  source/Windows.Storage/packages.config
  source/nanoFramework.Windows.Storage.DELIVERABLES.nuspec
  source/nanoFramework.Windows.Storage.nuspec
Labels: Type: dependencies

#36 Fix for GetFileFromPath, name not being set
  source/Windows.Storage/StorageFile.cs
Labels: Type: bug
